### ISSUE TITLE
Quick Sorting Description File Required

### ISSUE THREAD

**Issue by sukehiro-San** [sukehiro-San/SortingVisualizer#11]
Quick Sort algorithm complete description required that include it's working, algorithm, and Space and Time Complexity Analysis. It should be in a separate folder called Descriptions in the root folder with a .md /  .txt / or raw file format

**Comment by Harsh-bartariya** [comment]
Please assign it to me

**Comment by SalientAuthor** [comment]
please assign this work to me.

**Comment by Deepakv14** [comment]
Can you assign me this task?
