### ISSUE TITLE
Bubble Sorting description file required

### ISSUE THREAD

**Issue by sukehiro-San** [sukehiro-San/SortingVisualizer#13]
Bubble Sort algorithm complete description required that include it's working, algorithm, and Space and Time Complexity Analysis. It should be in a separate folder called Descriptions in the root folder with a .md /  .txt / or raw file format

**Comment by AlexInes** [comment]
I can do it.

**Comment by Ashutoshonly** [comment]
Kindly assign me this issue....i think i can solve it
