### ISSUE TITLE
Selection Sorting algorithm description file required

### ISSUE THREAD

**Issue by sukehiro-San** [sukehiro-San/SortingVisualizer#14]
Selection Sort algorithm complete description required that include it's working, algorithm, and Space and Time Complexity Analysis. It should be in a separate folder called Descriptions in the root folder with a .md /  .txt / or raw file format

**Comment by Himanshi1207** [comment]
Can you assign me this ?

**Comment by sukehiro-San** [comment]
@Himanshi1207 kindly create and edit a markdown file with the related sorting algorithm name, for e.g. **bubblesort.md** in the description folder of the root directory. Kindly use appropriate _heading, subheadings, bold & italic texts and line breaks_. Your contribution will be appreciated.

**Comment by Himanshi1207** [comment]
Thanks @sukehiro-San for the information.

**Comment by Himanshi1207** [comment]
Hello,
I have made a .md file can you plz check it once and let me know.

**Comment by sukehiro-San** [comment]
Sorry @Himanshi1207, I couldn't find the specified file that you have created. Also I couldn't find the forked repository in your list of repositories. Please create a pull request after you've successfully created the file. This way I can easily find your specified file.

**Comment by Himanshi1207** [comment]
i have made a pull request plz check.

**Comment by sukehiro-San** [comment]
Thank you, _@Himanshi1207_, for your valuable contribution [#16] towards this project and to the open-source community. You can further reach out to me for any kind of assistance at sunnykewat99@gmail.com .

**Comment by Himanshi1207** [comment]
Thank you!
Can we connect on linkedin?
